/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programi;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author Pc
 */
public class ndryshoFaturen extends javax.swing.JFrame {

    public static String produkti , pershkrimi,sasiaNeStok,cmimi,nrIdentifikuesFillestar,dataFillestare;
    public static int data = 1,tvsh,idProduktit;
    private int nrRreshtit = 1,totaliProdukteve = 0;
    private int klientiSelektuar = -1;
    private ArrayList<String> kId = new ArrayList<String>();
    /**
     * Creates new form ndryshoFaturen
     */
    public ndryshoFaturen() {
        initComponents();
        
        this.setBackground(Color.yellow);
        this.setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        fKomenti.setLineWrap(true);
        fKomenti.setWrapStyleWord(true);
        TableColumnModel t = jTable1.getColumnModel();
        t.getColumn(0).setPreferredWidth(40);
        t.getColumn(1).setPreferredWidth(60);
        t.getColumn(2).setPreferredWidth(170);
        t.getColumn(3).setPreferredWidth(270);
        t.getColumn(4).setPreferredWidth(50);
        t.getColumn(5).setPreferredWidth(50);
        t.getColumn(6).setPreferredWidth(97);
        t.getColumn(7).setPreferredWidth(97);  
        
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            jTable1.getTableHeader().setResizingAllowed(true);
            JTableHeader h = jTable1.getTableHeader();
            h.setOpaque(false);
            h.setBackground(Color.red);
            h.setForeground(Color.DARK_GRAY);
           
            h.setFont(new Font("Arial", Font.BOLD, 12));
        
        loadKlienti();
        teDhenatFillestare();
        tabelaFillestare();
        klientiFillestar();
        buttonGroup1.add(cash);
        buttonGroup1.add(bank);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        produkti1 = new javax.swing.JTextField();
        pershkrimi1 = new javax.swing.JTextField();
        njesia1 = new javax.swing.JTextField();
        sasia1 = new javax.swing.JTextField();
        cmimi1 = new javax.swing.JTextField();
        shtoProduktin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fKomenti = new javax.swing.JTextArea();
        printo = new javax.swing.JButton();
        choice1 = new java.awt.Choice();
        selektoProduktin = new javax.swing.JButton();
        alert = new javax.swing.JLabel();
        shtoKlientin = new javax.swing.JButton();
        cash = new javax.swing.JRadioButton();
        bank = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        printo1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        kEmri = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kNrBiznesit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kAdresa = new javax.swing.JTextField();
        kNrFiskal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        kNrTelefoni = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        fshiProduktin = new javax.swing.JButton();
        alert1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totaliField = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        nrIdentifikues = new javax.swing.JLabel();
        idenField = new javax.swing.JTextField();
        dataT = new javax.swing.JLabel();
        dataField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(119, 236, 145));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Produkti:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Klienti:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Pershkrimi:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Njesia:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Sasia:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Cmimi:");

        produkti1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        produkti1.setToolTipText("");

        pershkrimi1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        pershkrimi1.setToolTipText("");

        njesia1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        njesia1.setToolTipText("");

        sasia1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        sasia1.setToolTipText("");
        sasia1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sasia1KeyPressed(evt);
            }
        });

        cmimi1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cmimi1.setToolTipText("");
        cmimi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmimi1KeyPressed(evt);
            }
        });

        shtoProduktin.setBackground(new java.awt.Color(0, 153, 255));
        shtoProduktin.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        shtoProduktin.setForeground(new java.awt.Color(255, 255, 255));
        shtoProduktin.setText("ShtoProduktin");
        shtoProduktin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shtoProduktin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                shtoProduktinMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Komenti:");

        fKomenti.setColumns(20);
        fKomenti.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fKomenti.setRows(5);
        jScrollPane2.setViewportView(fKomenti);

        printo.setBackground(new java.awt.Color(255, 255, 0));
        printo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        printo.setText("Ndrysho");
        printo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                printoMousePressed(evt);
            }
        });

        choice1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N

        selektoProduktin.setBackground(new java.awt.Color(51, 51, 255));
        selektoProduktin.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        selektoProduktin.setForeground(new java.awt.Color(255, 255, 255));
        selektoProduktin.setText("Selekto Produktin");
        selektoProduktin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selektoProduktin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                selektoProduktinMousePressed(evt);
            }
        });

        alert.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        alert.setForeground(new java.awt.Color(255, 51, 0));
        alert.setToolTipText("");

        shtoKlientin.setBackground(new java.awt.Color(51, 51, 255));
        shtoKlientin.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        shtoKlientin.setForeground(new java.awt.Color(255, 255, 255));
        shtoKlientin.setText("ShtoKlientin");
        shtoKlientin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shtoKlientin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                shtoKlientinMousePressed(evt);
            }
        });

        cash.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cash.setText("Cash");
        cash.setContentAreaFilled(false);

        bank.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        bank.setText("Bankë");
        bank.setContentAreaFilled(false);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("Pagesa:");

        printo1.setBackground(new java.awt.Color(204, 51, 0));
        printo1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        printo1.setText("Anulo Ndryshimet");
        printo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                printo1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7))
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bank)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(shtoKlientin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pershkrimi1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(produkti1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(njesia1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sasia1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmimi1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selektoProduktin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shtoProduktin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(printo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(alert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shtoKlientin, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(produkti1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pershkrimi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(njesia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sasia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selektoProduktin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shtoProduktin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmimi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cash)
                    .addComponent(bank)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(printo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printo1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setText("Emri:");

        kEmri.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        kEmri.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setText("NrBiznesit:");

        kNrBiznesit.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        kNrBiznesit.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setText("Adresa:");

        kAdresa.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        kAdresa.setToolTipText("");

        kNrFiskal.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        kNrFiskal.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel12.setText("NrTelefonit:");

        kNrTelefoni.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        kNrTelefoni.setToolTipText("");

        jTable1.setBackground(new java.awt.Color(255, 255, 254));
        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr", "ID", "Produkti", "Pershkrimi", "Sasia", "Njesia", "Cmimi", "Totali", "TVSH %"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(255, 255, 241));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/arrow.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        fshiProduktin.setBackground(new java.awt.Color(255, 255, 241));
        fshiProduktin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/x.png"))); // NOI18N
        fshiProduktin.setBorder(null);
        fshiProduktin.setContentAreaFilled(false);
        fshiProduktin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fshiProduktin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fshiProduktinMousePressed(evt);
            }
        });
        fshiProduktin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fshiProduktinActionPerformed(evt);
            }
        });

        alert1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        alert1.setForeground(new java.awt.Color(204, 0, 0));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel14.setText("NrFiskal:");

        totaliField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jButton9.setBackground(new java.awt.Color(255, 255, 241));
        jButton9.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton9.setText("Faturat");
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.setSelected(true);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton9MousePressed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 241));
        jButton10.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton10.setText("Ofertat");
        jButton10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton10.setBorderPainted(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.setSelected(true);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton10MousePressed(evt);
            }
        });

        nrIdentifikues.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nrIdentifikues.setText("Nr Identifikues:");

        idenField.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        idenField.setToolTipText("");

        dataT.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        dataT.setText("Data:");

        dataField.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        dataField.setToolTipText("");

        jLabel11.setText("YYYY-MM-DD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(kEmri, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(kNrBiznesit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(kAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(kNrFiskal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kNrTelefoni, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nrIdentifikues)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idenField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(totaliField, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(fshiProduktin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(alert1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(dataT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(50, 50, 50))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(kEmri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kNrBiznesit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kNrFiskal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kNrTelefoni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrIdentifikues, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fshiProduktin, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(totaliField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(alert1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataT)
                    .addComponent(dataField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void teDhenatFillestare(){
        idenField.setText(nrIdentifikuesFillestar);
        dataField.setText(dataFillestare);
    } 
    public void klientiFillestar(){
        try{
            Statement s = prg.con().createStatement();
            ResultSet rs = s.executeQuery("Select klienti,nrBiznesit,adresa,nrFiskal,nrTelefonit,pagesa,komenti from daljetFaturore where nrIdentifikues = '"+nrIdentifikuesFillestar+"'");
            while(rs.next()){
                kEmri.setText(rs.getString(1));
                kNrBiznesit.setText(rs.getString(2));
                kAdresa.setText(rs.getString(3));
                kNrFiskal.setText(rs.getString(4));
                kNrTelefoni.setText(rs.getString(5));
                fKomenti.setText(rs.getString(7));
                String pagesa = rs.getString(6);
                if (pagesa.equals("Cash")) {
                    cash.setSelected(true);
                }else
                    bank.setSelected(true);
                
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    public void tabelaFillestare(){
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        DecimalFormat df = new DecimalFormat("0.00");
        try{
            Statement s = prg.con().createStatement();
            ResultSet rs = s.executeQuery("Select IdProduktit,produkti,pershkrimi,sasia,njesia,cmimiPerNjesi,tvsh from daljetFaturore where nrIdentifikues = '"+nrIdentifikuesFillestar+"'");
            while(rs.next()){
                Vector v = new Vector();
                
                v.add(nrRreshtit);
                v.add(rs.getString(1)); //id
                v.add(rs.getString(2)); //produkti
                v.add(rs.getString(3)); // pershkrimi
                
                int sasia = rs.getInt(4); // sasia
                v.add(sasia);             // sasia
                v.add(rs.getString(5));     //njesia
                double cmimi = rs.getDouble(6); // cmimi
                df.format(cmimi);               // cmimi
                v.add(cmimi+"€");               // cmimi
                double totali = cmimi*sasia;    //totali
                String t = String.format("%.2f", totali);              //totali
                v.add(t+"€");              //totali
                v.add(rs.getString(7));         //tvsh
                
                dt.addRow(v);
                nrRreshtit++;
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    public void loadKlienti(){
        
        try{
            Statement s = prg.con().createStatement();
            ResultSet rs = s.executeQuery("Select Emri,KlientiID from Klienti");
            while(rs.next()){
                choice1.add(rs.getString(1));
                kId.add(rs.getString(2));
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    public static void  loadData(){
        produkti1.setText(produkti);
        pershkrimi1.setText(pershkrimi);
        sasia1.setText("1");
        cmimi1.setText(cmimi);
        njesia1.setText("c");
    }
    public void loadtable(){
                      
        Vector v = new Vector();       
        v.add(nrRreshtit);
        v.add(idProduktit);
        v.add(produkti1.getText());
        v.add(pershkrimi1.getText());
        v.add(sasia1.getText());     
        v.add(njesia1.getText());
        //        
        String cmim = cmimi1.getText();
        
            if (cmim.contains("€") && cmim.contains(".")) {
                cmimi1.setText(cmim);
                v.add(cmim);
            }else if(cmim.contains("€") && !cmim.contains(".")){
                cmim = cmim.replace("€", ".0");
                cmimi1.setText(cmim+"€");
                v.add(cmim+"€");
            }else if(!cmim.contains("€") && cmim.contains(".")){
                cmimi1.setText(cmim+"€");
                v.add(cmim+"€");
            }else if(!cmim.contains("€") && !cmim.contains(".")){
                cmimi1.setText(cmim+".0 €");
                v.add(cmim+".0 €");
            }
        
        v.add(totaliRreshtit()+" €");
        v.add(tvsh+"%");
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(v);
        nrRreshtit++;
    }
    private void shtoProduktinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shtoProduktinMousePressed

        if (kontrolloSasin()) {
            alert.setText("Sasia eshte me e madhe se Stoku!");
        }

        loadtable();
        llogaritTotalin();

    }//GEN-LAST:event_shtoProduktinMousePressed
    public void llogaritTotalin(){
        int rows = jTable1.getRowCount();
        if (rows == 0) {                                   
                totaliField.setText("Totali i Produkteve eshte: 0.00 €");                      
        }else{
            for (int i = 0; i < rows; i++) {
                String totali = jTable1.getModel().getValueAt(i, 7).toString();
                String heqjaEuro = totali.substring(0, totali.length()-1);
                double vlera = Double.parseDouble(heqjaEuro);           
                totaliProdukteve += vlera;
                String x = String.valueOf(totaliProdukteve);
                totaliField.setText("Totali i Produkteve eshte: "+x+" €");   
                
            }
        }
        totaliProdukteve = 0;
    }
    public double totaliRreshtit(){
        String cmimi = cmimi1.getText();
        cmimi = cmimi.substring(0, cmimi.length() - 1);
        int s = Integer.parseInt(sasia1.getText());
        double c = Double.parseDouble(cmimi);
        
        return c*s;
    }
    public boolean kontrolloSasin(){
        int s = Integer.parseInt(sasia1.getText());
        int ss = Integer.parseInt(sasiaNeStok);
        if (s > ss) {
            return true;
        }
        return false;
    }
    private void selektoProduktinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selektoProduktinMousePressed
        SelektoProduktin s = new SelektoProduktin();
        SelektoProduktin.thirrja = "ndryshoF";
        s.setVisible(true);
    }//GEN-LAST:event_selektoProduktinMousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        Transaksionet r= new Transaksionet();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MousePressed

    private void fshiProduktinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fshiProduktinMousePressed

        if (jTable1.getSelectionModel().isSelectionEmpty()) {
            alert1.setText("Nje Rresht Duhet Te Selektohet!");

        }else{
            int row = jTable1.getSelectedRow();
            ((DefaultTableModel)jTable1.getModel()).removeRow(row);
            llogaritTotalin();
            rregulloNumratRendor(row);
            nrRreshtit--;
        }
    }//GEN-LAST:event_fshiProduktinMousePressed
    public void rregulloNumratRendor(int row){
        row++;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            int vlera = Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(i, 0)));
            if (row < vlera) {
                
                
                Object x = (Integer) row;
                jTable1.setValueAt(x, i, 0);
                row++;
            }
        }
    }
    private void fshiProduktinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fshiProduktinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fshiProduktinActionPerformed

    private void jButton9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MousePressed

        String pathName = Login.folderiFaturave;
        try {
            Desktop.getDesktop().open(new File(pathName));
        } catch (IOException ex) {
            Logger.getLogger(Fillimi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9MousePressed

    private void jButton10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MousePressed
        String pathName = Login.folderiOfertave;
        try {
            Desktop.getDesktop().open(new File(pathName));
        } catch (IOException ex) {
            Logger.getLogger(Fillimi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10MousePressed

    private void sasia1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sasia1KeyPressed
       Programi.numberCheck(evt);
    }//GEN-LAST:event_sasia1KeyPressed

    private void cmimi1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmimi1KeyPressed
        Programi.numberCheck(evt);
    }//GEN-LAST:event_cmimi1KeyPressed

    private void printo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printo1MousePressed
        dispose();
        Transaksionet t = new Transaksionet();
        t.setVisible(true);
    }//GEN-LAST:event_printo1MousePressed

    private void shtoKlientinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shtoKlientinMousePressed
        klientiSelektuar = choice1.getSelectedIndex();
        klientiSelektuar++;
        for (int i = 0; i < kId.size(); i++) {
            if (klientiSelektuar == (i+1)) {
                try{
                    Statement s = prg.con().createStatement();
                    ResultSet rs = s.executeQuery("Select * from Klienti where KlientiID = "+kId.get(i));
                    while(rs.next()){
                        kEmri.setText(rs.getString(2));
                        kNrBiznesit.setText(rs.getString(3));
                        kAdresa.setText(rs.getString(4));
                        kNrFiskal.setText(rs.getString(5));
                        kNrTelefoni.setText(rs.getString(6));
                    }
                }catch(SQLException e){
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_shtoKlientinMousePressed

    private void printoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printoMousePressed
        alert1.setText(" ");
        fshiFaturen(nrIdentifikuesFillestar);  
        pdfFatura.lloji = "Faturë";
        String emriKlientit = kEmri.getText();
        String nrBiznesit = kNrBiznesit.getText();
        String adresa = kAdresa.getText();
        String nrFiskal = kNrFiskal.getText();
        String nrTelefonit = kNrTelefoni.getText();
        String komenti = fKomenti.getText();
        String nrIdentifikues = idenField.getText();
        String pagesa = kontrolloPagesen();
        String data = data();
        boolean bool = true; 
        double vmtf = 0;
        if (pagesa.equals("alert")) {
            bool = false;
        }
        if (checkInputet()) {
            bool = false;
        }
        if (kontrolloNrIdentifikues()) {
            bool = false;
            alert1.setText("Egziston fature me kete numer!");
        }
        if(bool == true){
        double cmimiPaTvsh = 0,tvsh = 0 ,cmimiMeTvsh = 0;
        DecimalFormat df = new DecimalFormat("0.00");
        df.format(cmimiPaTvsh);
        df.format(tvsh);
        df.format(cmimiMeTvsh);
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        
        for (int i = 1; i <= nRow; i++) {
               
               
                    
               String sas = String.valueOf(dtm.getValueAt(i-1, 4));
                int sasia = Integer.parseInt(sas);
               String alo = String.valueOf(dtm.getValueAt(i-1, 3));
                String stringTvsh = String.valueOf(dtm.getValueAt(i-1,8));
                String heqjaPerqindjes = stringTvsh.substring(0, stringTvsh.length()-1);
                double tv = Double.parseDouble(heqjaPerqindjes);
                
                String cpt = String.valueOf(dtm.getValueAt(i-1, 6));
                String heqjaEuro= cpt.substring(0, cpt.length()-1);
                
                double hqD = Double.parseDouble(heqjaEuro);
                   
                double llogaritTvsh = -(hqD/(tv/100.0+1)-hqD);
                double llogcpt = (hqD-llogaritTvsh) * sasia;
                
                
                cmimiPaTvsh += llogcpt;
                
                   
                    double llogtv = -(hqD/(tv/100.0+1)-hqD);
                tvsh += llogtv*sasia;
                
                   
                
            }
        
        int faturaID = 0;       
        cmimiMeTvsh = 0;
        cmimiMeTvsh = cmimiPaTvsh+tvsh;
           
        try{
           Statement s = prg.con().createStatement();
           s.execute("Insert into fatura (dataFatures,Klienti,cmimiPaTvsh,tvsh,cmimiMeTvsh,pagesa,nrIdentifikues) values ('"+data+"','"+emriKlientit+"','"+cmimiPaTvsh+"','"+tvsh+"','"+cmimiMeTvsh+"','"+pagesa+"','"+nrIdentifikues+"')");
           
           s.execute("Insert into transaksionet (kategoria,nrIdentifikimit,totali,dataTransaksionet,perdoruesi,klienti) values ('Faturë','"+nrIdentifikues+"','"+cmimiMeTvsh+"','"+data+"','"+prg.emriPerdoruesit+"','"+emriKlientit+"')");

           ResultSet rs =  s.executeQuery("Select faturaID from fatura where nrIdentifikues = '"+nrIdentifikues+"'");
           while(rs.next()){
               faturaID = rs.getInt(1);
           }
        }catch(SQLException e){
            e.printStackTrace();
        }
        
        for (int i = 0; i < nRow; i++) {
            Vector v = new Vector();
            for (int j = 0; j < nCol; j++) {
                String s = String.valueOf(dtm.getValueAt(i, j));
                v.add(s);
            }
            try{
                
                int sasia = Integer.parseInt(String.valueOf(v.get(4)));
                
                String t = String.valueOf(v.get(6));
                String fx = t.substring(0,t.length()-1);
                double cpn = Double.parseDouble(fx);
                
                String t1 = String.valueOf(v.get(8));
                String fx1 = t1.substring(0,t1.length()-1);
                int tv = Integer.parseInt(fx1);             
                
                double tvshCmim = -(cpn/(tv/100.0+1)-cpn);
                
                
                double cPaTvsh = cpn - tvshCmim;
                
                double cmt = cPaTvsh + tvshCmim;
                
                double vmt = cmt*sasia;
                
                df.format(cpn);
                df.format(cmt);
                df.format(vmt);
                
                vmtf = Math.round(vmt * 100.0) / 100.0;
                double cmtf = Math.round(cmt * 100.0) / 100.0;
                double cpnf = Math.round(cPaTvsh * 100.0) / 100.0;
                
                
                Statement s = prg.con().createStatement();
                String s1 = String.valueOf(v.get(8));
                String heqjaLaserike = s1.substring(0, s1.length()-1);
                s.execute("Insert into daljetFaturore (klienti,nrBiznesit,adresa,nrFiskal,nrTelefonit,nrRendor,produkti,pershkrimi,sasia,njesia,cmimiPerNjesi,tvsh,cmimiMeTvsh,vleraMeTvsh,nrIdentifikues,faturaId,idProduktit,pagesa,komenti)"
                        + " values ('"+emriKlientit+"','"+nrBiznesit+"','"+adresa+"','"+nrFiskal+"','"+nrTelefonit+"','"+v.get(0)+"','"+v.get(2)+"','"+v.get(3)+"','"+v.get(4)+"','"
                        +v.get(5)+"','"+cpnf+"','"+heqjaLaserike+"%','"+cmtf+" €','"+vmtf+" €','"+nrIdentifikues+"','"+faturaID+"','"+v.get(1)+"','"+pagesa+"','"+komenti+"')");
                
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
        pdfFatura.klienti = emriKlientit;
        pdfFatura.nrBiznesit = nrBiznesit;
        pdfFatura.adresa = adresa;
        pdfFatura.nrFiskal = nrFiskal;
        pdfFatura.nrTelefonit = nrTelefonit;
        pdfFatura.data = data;
        pdfFatura.nrIdentifikues = nrIdentifikues;
        pdfFatura.komenti = komenti;
        pdfFatura.shkruaj();
        pdfFatura.rreshtat = dtm.getRowCount();
        minusoStokin();
        Transaksionet t = new Transaksionet();
        t.setVisible(true);
        dispose();
        }
        
        
    }//GEN-LAST:event_printoMousePressed
    public boolean kontrolloNrIdentifikues(){
        boolean egziston = false;
        String nrId = idenField.getText();
        try{
            Statement s = prg.con().createStatement();
            ResultSet rs = s.executeQuery("Select nrIdentifikues from Fatura");
            while(rs.next()){
                if (nrId.equals(rs.getString(1))) {
                    egziston = true;
                }
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        return egziston;
    }
   
    public void fshiFaturen(String nrId){
        String klienti = null;
          try{
              Statement s = prg.con().createStatement();
              s.execute("Delete from transaksionet where nrIdentifikimit = '"+nrId+"'");
              ResultSet rs = s.executeQuery("Select sasia,idProduktit,klienti from daljetFaturore where nrIdentifikues = '"+nrId+"'");
              while(rs.next()){
                  klienti = rs.getString(3);
                    int sasia = rs.getInt(1);
                    int id = rs.getInt(2);
                    Statement s2 = prg.con().createStatement();
                    s2.execute("Update produkti set sasia = sasia+"+sasia+" where ProduktiID = "+id);                                                      
              }
              Statement s3 = prg.con().createStatement();
              s3.execute("Delete from daljetFaturore where nrIdentifikues = '"+nrId+"'");
              s3.execute("Delete from fatura where nrIdentifikues = '"+nrId+"'");
              
               File myObj = new File(Login.folderiFaturave+"//"+klienti+" #"+nrId+".pdf"); 
              if (myObj.delete()) {
                System.out.println("Deleted");
            }else
                  System.out.println("Failed to delete");
          }catch(SQLException e){
              e.printStackTrace();
          }
    }
    public void minusoStokin(){
        int sasia = 0,produktiId = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            
                produktiId = Integer.parseInt(String.valueOf(jTable1.getValueAt(i, 1)));
                sasia = Integer.parseInt(String.valueOf(jTable1.getValueAt(i, 4)));
                
                try{
                    Statement s = prg.con().createStatement();
                    s.execute("Update Produkti set Sasia = Sasia -"+sasia+" where ProduktiID = "+produktiId);
                }catch(SQLException e){
                    e.printStackTrace();
                }
        }
    }
    public boolean checkInputet(){
        boolean t = false;
        
        if (produkti1.getText().length() > 30) {
            alert.setText("Produkti ka mbi 30 karaktere!");
        }
        if (pershkrimi1.getText().length() > 120) {
            alert.setText("Pershkrimi ka mbi 120 karaktere!");
        }
        if (njesia1.getText() == null || njesia1.getText().trim().isEmpty()) {
            alert.setText("Njesia nuk lejohet e zbrazet!");
        }
        if (njesia1.getText().length() > 7) {
            alert.setText("Njesia ka mbi 120 karaktere!");
        }
        if (sasia1.getText() == null || sasia1.getText().trim().isEmpty()) {
            alert.setText("Sasia nuk lejohet e zbrazet!");
        }
        if (cmimi1.getText().length() > 20) {
            alert.setText("Cmimi ka mbi 20 karaktere!");
        }
        if (cmimi1.getText() == null || cmimi1.getText().trim().isEmpty()) {
            alert.setText("Cmimi nuk lejohet e zbrazet!");
        }
        
        return t;
    }
    public String data(){
        
        LocalDate dateObj = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String date = dateObj.format(formatter);
        return date;
    
    }
    
   public String kontrolloPagesen(){
       String lloji = null;
        if (cash.isSelected()) {
            lloji =  "Cash";
            pdfFatura.pagesa = "Cash";
        }else if (bank.isSelected()){
            lloji = "Bankarë";
            pdfFatura.pagesa = "Bankarë";
        }
        else{
            alert.setText("Cash ose Bankë duhet te zgjidhet!");
            lloji = "alert";
        }
         return lloji;  
   }
    public String date(){
        LocalDate dateObj = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String date = dateObj.format(formatter);
        return date;
    }
    public String getYear(){
        LocalDate dateObj = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy");
        String date = dateObj.format(formatter);
        return date;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ndryshoFaturen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ndryshoFaturen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ndryshoFaturen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ndryshoFaturen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ndryshoFaturen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JLabel alert1;
    private javax.swing.JRadioButton bank;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cash;
    private java.awt.Choice choice1;
    private static javax.swing.JTextField cmimi1;
    private javax.swing.JTextField dataField;
    private javax.swing.JLabel dataT;
    private javax.swing.JTextArea fKomenti;
    private javax.swing.JButton fshiProduktin;
    private javax.swing.JTextField idenField;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kAdresa;
    private javax.swing.JTextField kEmri;
    private javax.swing.JTextField kNrBiznesit;
    private javax.swing.JTextField kNrFiskal;
    private javax.swing.JTextField kNrTelefoni;
    private static javax.swing.JTextField njesia1;
    private javax.swing.JLabel nrIdentifikues;
    private static javax.swing.JTextField pershkrimi1;
    private javax.swing.JButton printo;
    private javax.swing.JButton printo1;
    private static javax.swing.JTextField produkti1;
    private static javax.swing.JTextField sasia1;
    private javax.swing.JButton selektoProduktin;
    private javax.swing.JButton shtoKlientin;
    private javax.swing.JButton shtoProduktin;
    private javax.swing.JLabel totaliField;
    // End of variables declaration//GEN-END:variables
}
