/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programi;

import java.awt.geom.RoundRectangle2D;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Pc
 */
public class regjistroFaturen extends javax.swing.JFrame {
    private int nrRreshtit = 1;
    private ArrayList<String> id  = new ArrayList<String>();
    /**
     * Creates new form regjistroFaturen
     */
    public regjistroFaturen() {
        initComponents();
        kategoria();
        this.setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        TableColumnModel t = jTable1.getColumnModel();
        t.getColumn(0).setPreferredWidth(40);
        t.getColumn(1).setPreferredWidth(170);
        t.getColumn(2).setPreferredWidth(270);
        t.getColumn(3).setPreferredWidth(50);
        t.getColumn(4).setPreferredWidth(50);
        t.getColumn(5).setPreferredWidth(97);
        t.getColumn(6).setPreferredWidth(97);
        t.getColumn(7).setPreferredWidth(97);  
    }
     public void kategoria(){
        try{
            Statement s = prg.con().createStatement();
            ResultSet rs = s.executeQuery("Select Emri,KategoriaID from Kategoria");
            while(rs.next()){
                choice1.add(rs.getString(1));
                id.add(rs.getString(2));
                
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        produkti = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pershkrimi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sasia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmimif = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fatura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        furnitori = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        alert1 = new javax.swing.JLabel();
        alert2 = new javax.swing.JLabel();
        alert3 = new javax.swing.JLabel();
        alert4 = new javax.swing.JLabel();
        alert6 = new javax.swing.JLabel();
        alert5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        fshiProduktin = new javax.swing.JButton();
        alert7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmimis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(119, 236, 145));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Produkti:");

        produkti.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        produkti.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Pershkrimi:");

        pershkrimi.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        pershkrimi.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Sasia:");

        sasia.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        sasia.setToolTipText("");
        sasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sasiaKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Cmimi F:");

        cmimif.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        cmimif.setToolTipText("");
        cmimif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmimifKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Fatura:");

        fatura.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        fatura.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Furnitori:");

        furnitori.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        furnitori.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Kategoria:");

        choice1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 255, 241));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/arrow.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ShtoProduktin");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        alert1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        alert1.setForeground(new java.awt.Color(255, 0, 0));

        alert2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        alert2.setForeground(new java.awt.Color(255, 0, 0));

        alert3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        alert3.setForeground(new java.awt.Color(255, 0, 0));

        alert4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        alert4.setForeground(new java.awt.Color(255, 0, 0));

        alert6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        alert6.setForeground(new java.awt.Color(255, 0, 0));

        alert5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        alert5.setForeground(new java.awt.Color(255, 0, 0));

        jTable1.setBackground(new java.awt.Color(255, 255, 254));
        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr", "Produkti", "Pershkrimi", "Sasia", "Cmimi F", "Cmimi S", "Fatura", "Furnitori", "Kategoria"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Shto Produktet");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        fshiProduktin.setBackground(new java.awt.Color(255, 255, 241));
        fshiProduktin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/x.png"))); // NOI18N
        fshiProduktin.setBorder(null);
        fshiProduktin.setContentAreaFilled(false);
        fshiProduktin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fshiProduktin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fshiProduktinMousePressed(evt);
            }
        });

        alert7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        alert7.setForeground(new java.awt.Color(204, 0, 0));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Cmimi S:");

        cmimis.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        cmimis.setToolTipText("");
        cmimis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmimisKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produkti, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alert1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sasia, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alert3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmimif, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alert4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pershkrimi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alert2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmimis)
                    .addComponent(fatura, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(furnitori, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choice1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(alert5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alert6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alert7, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(fshiProduktin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alert5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(produkti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(fatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(alert1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pershkrimi)
                    .addComponent(furnitori)
                    .addComponent(alert6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alert2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choice1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sasia)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alert3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmimif, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(alert4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmimis))))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(alert7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fshiProduktin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        check();
    }//GEN-LAST:event_jButton1MousePressed
    public void check(){
        alert1.setText("");
        alert4.setText("");
        if (produkti.getText() == null || produkti.getText().trim().isEmpty()) {
            alert1.setText("!");
            return;
        }if (cmimif.getText() == null || cmimif.getText().trim().isEmpty()) {
            alert4.setText("!");
            return;
        }
        shtoNeTabele();
    }
    public void shtoNeTabele(){
        
        Vector v = new Vector();
        v.add(nrRreshtit);
        v.add(produkti.getText());
        v.add(pershkrimi.getText());
        v.add(sasia.getText());
        v.add(cmimif.getText());
        v.add(cmimis.getText());
        v.add(fatura.getText());
        v.add(furnitori.getText());
        int k = choice1.getSelectedIndex();
        v.add(id.get(k));
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.addRow(v);
        nrRreshtit++;
    }
    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        Stoku s = new Stoku();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MousePressed

    private void cmimifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmimifKeyTyped
        Programi.numberCheck(evt);
    }//GEN-LAST:event_cmimifKeyTyped

    private void sasiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sasiaKeyTyped
        Programi.numberCheck(evt);
    }//GEN-LAST:event_sasiaKeyTyped

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        alert7.setText("");
        
        String date = tt();
       
        
        if (jTable1.getRowCount() == 0) {
            alert7.setText("Nuk ka asnje produkt per tu shtuar!");
        }else{
            try {
                Statement s = prg.con().createStatement();
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    Vector v = new Vector();
                    for (int j = 0; j < jTable1.getColumnCount(); j++) {
                        v.add(jTable1.getValueAt(i, j));
                    }
                     
                     s.execute("Insert into Produkti (Emri,Pershkrimi,Sasia,Cmimi,Furnitori,Fatura,DataRegjistrimit,KategoriaID,CmimiFurnizimit) values ('"+v.get(1)+"','"+v.get(2)+"','"+v.get(3)+"','"+v.get(5)+"','"+v.get(7)+"','"+v.get(6)+"','"+date+"','"+v.get(8)+"','"+v.get(4)+"')");
                     
                }
            } catch (SQLException ex) {
                alert7.setText("Fatura nuk mund te shtohet");
            }
            alert7.setText("Fatura u shtua me sukses");
                     DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                     dtm.setRowCount(0);
                     produkti.setText("");
                     pershkrimi.setText("");
                     sasia.setText("");
                     cmimif.setText("");
                     fatura.setText("");
                     furnitori.setText("");
                     cmimis.setText("");
                     
                     
                    
        }
    }//GEN-LAST:event_jButton3MousePressed
    public String tt() {
        LocalDate dateObj = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String date = dateObj.format(formatter);
        return date;
    }
    private void fshiProduktinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fshiProduktinMousePressed
        alert7.setText("");
        if (jTable1.getSelectionModel().isSelectionEmpty()) {
            alert7.setText("Nje Rresht Duhet Te Selektohet!");
            
        }else{
            int row = jTable1.getSelectedRow();   
            ((DefaultTableModel)jTable1.getModel()).removeRow(row);                
            rregulloNumratRendor(row);
            nrRreshtit--;
        }
    }//GEN-LAST:event_fshiProduktinMousePressed

    private void cmimisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmimisKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cmimisKeyTyped
     public void rregulloNumratRendor(int row){
        row++;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            int vlera = Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(i, 0)));
            if (row < vlera) {
                
                
                Object x = (Integer) row;
                System.out.println(row);
                jTable1.setValueAt(x, i, 0);
                row++;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regjistroFaturen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regjistroFaturen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regjistroFaturen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regjistroFaturen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regjistroFaturen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert1;
    private javax.swing.JLabel alert2;
    private javax.swing.JLabel alert3;
    private javax.swing.JLabel alert4;
    private javax.swing.JLabel alert5;
    private javax.swing.JLabel alert6;
    private javax.swing.JLabel alert7;
    private java.awt.Choice choice1;
    private javax.swing.JTextField cmimif;
    private javax.swing.JTextField cmimis;
    private javax.swing.JTextField fatura;
    private javax.swing.JButton fshiProduktin;
    private javax.swing.JTextField furnitori;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pershkrimi;
    private javax.swing.JTextField produkti;
    private javax.swing.JTextField sasia;
    // End of variables declaration//GEN-END:variables
}
