/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package programi;

import com.itextpdf.text.log.Logger;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.io.IOException;
import java.lang.System.Logger.Level;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import static programi.Faturo.idProduktit;
import static programi.Faturo.tvsh;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import javax.swing.table.JTableHeader;
/**
 *
 * @author BERDYNA
 */
public class Shitje extends javax.swing.JFrame {
    public static String produkti,pershkrimi,komenti;
    public static double cmimiShitjes;
    public static int sasia,idProduktit;
    int nrRreshtit = 1;
            
    /** Creates new form Shitje */
    public Shitje() {
        initComponents();
        this.setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        TableColumnModel t = jTable1.getColumnModel();
        t.getColumn(0).setPreferredWidth(35);
        t.getColumn(1).setPreferredWidth(45);
        t.getColumn(2).setPreferredWidth(140);
        t.getColumn(3).setPreferredWidth(235);
        t.getColumn(4).setPreferredWidth(45);
        t.getColumn(5).setPreferredWidth(45);
        t.getColumn(6).setPreferredWidth(80);
        t.getColumn(7).setPreferredWidth(80);
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            jTable1.getTableHeader().setResizingAllowed(true);
            JTableHeader h = jTable1.getTableHeader();
            h.setOpaque(false);
            h.setBackground(Color.red);
            h.setForeground(Color.DARK_GRAY);
           
            h.setFont(new Font("Arial", Font.BOLD, 14));
    }
    public static void shtoData(){
        produktiField.setText(produkti);
        pershkrimiField.setText(pershkrimi);
        cmimiField.setText(String.valueOf(cmimiShitjes));
        sasiaField.setText("1");
        kohaField.setText("6");
    }
    public void shtoNeTabele(){                      
        Vector v = new Vector();     
        
        v.add(nrRreshtit);
        if(idProduktit > 0){
            v.add(idProduktit);
        }else
            v.add(0);
        v.add(produktiField.getText());
        v.add(pershkrimiField.getText());
        v.add(sasiaField.getText());     
        v.add(njesiaField.getText());
        v.add(cmimiField.getText()+" €");
        v.add(llogaritRreshtin()+" €");        
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(v);
        nrRreshtit++;
    
    }
    public double llogaritRreshtin(){
        int sasia = Integer.parseInt(sasiaField.getText());
        double cmimi = Double.parseDouble(cmimiField.getText());
        
        double sum = sasia*cmimi;
        return sum;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selektoProduktin = new javax.swing.JButton();
        shtoProduktin = new javax.swing.JButton();
        proT = new javax.swing.JLabel();
        produktiField = new javax.swing.JTextField();
        perT = new javax.swing.JLabel();
        pershkrimiField = new javax.swing.JTextField();
        sasT = new javax.swing.JLabel();
        sasiaField = new javax.swing.JTextField();
        cmiT = new javax.swing.JLabel();
        cmimiField = new javax.swing.JTextField();
        pkT = new javax.swing.JLabel();
        kohaField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sasT1 = new javax.swing.JLabel();
        njesiaField = new javax.swing.JTextField();
        alert1 = new javax.swing.JLabel();
        printo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(119, 236, 145));

        selektoProduktin.setBackground(new java.awt.Color(51, 51, 255));
        selektoProduktin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        selektoProduktin.setForeground(new java.awt.Color(255, 255, 255));
        selektoProduktin.setText("Selekto Produktin");
        selektoProduktin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selektoProduktin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                selektoProduktinMousePressed(evt);
            }
        });

        shtoProduktin.setBackground(new java.awt.Color(0, 153, 255));
        shtoProduktin.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        shtoProduktin.setForeground(new java.awt.Color(255, 255, 255));
        shtoProduktin.setText("ShtoProduktin");
        shtoProduktin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shtoProduktin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                shtoProduktinMousePressed(evt);
            }
        });

        proT.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        proT.setText("Produkti:");

        produktiField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        produktiField.setToolTipText("");

        perT.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        perT.setText("Pershkrimi:");

        pershkrimiField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pershkrimiField.setToolTipText("");

        sasT.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        sasT.setText("Sasia:");

        sasiaField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sasiaField.setToolTipText("");

        cmiT.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cmiT.setText("Cmimi:");

        cmimiField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmimiField.setToolTipText("");

        pkT.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        pkT.setText("Periudha Kohore:");

        kohaField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        kohaField.setToolTipText("");

        jButton2.setBackground(new java.awt.Color(255, 255, 241));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/arrow.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 255, 254));
        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr", "ID", "Produkti", "Pershkrimi", "Sasia", "Njesia", "Cmimi", "Totali"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        sasT1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        sasT1.setText("Njesia:");

        njesiaField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        njesiaField.setText("C");
        njesiaField.setToolTipText("");

        alert1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        alert1.setForeground(new java.awt.Color(255, 51, 0));
        alert1.setToolTipText("");

        printo.setBackground(new java.awt.Color(255, 255, 0));
        printo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        printo.setText("Shitje");
        printo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                printoMousePressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 241));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/x.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 241));
        jButton10.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton10.setText("Garancionet");
        jButton10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton10.setBorderPainted(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.setSelected(true);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton10MousePressed(evt);
            }
        });

        jCheckBox1.setText("Printo Garancion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sasT, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sasiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(sasT1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(njesiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmiT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmimiField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pkT, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kohaField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(produktiField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(perT)
                                .addGap(10, 10, 10)
                                .addComponent(pershkrimiField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selektoProduktin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(shtoProduktin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alert1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(printo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(proT)
                                    .addComponent(perT)
                                    .addComponent(pershkrimiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(produktiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sasT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sasiaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmiT)
                                    .addComponent(cmimiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pkT)
                                    .addComponent(kohaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sasT1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(njesiaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selektoProduktin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shtoProduktin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(alert1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(printo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1)))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        Fillimi r= new Fillimi();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MousePressed

    private void shtoProduktinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shtoProduktinMousePressed
        alert1.setText(" ");
        boolean t = true;
       
        if (cmimiField.getText() == null || cmimiField.getText().equals("")) {
            alert1.setText("Produkti nuk ka cmim!");
            t =false;
        }
        if (kohaField.getText() == null || kohaField.getText().equals("")) {
            alert1.setText("Produkti nuk ka periudhë kohore!");
            t =false;
        }
        if (sasiaField.getText() == null || sasiaField.getText().equals("")) {
            alert1.setText("Sasia nuk eshte caktuar!");
            t = false;
            
        }else if(kontrolloSasin()){
                alert1.setText("Sasia eshte me e madhe se Stoki!");
            }
        if (t) {
            shtoNeTabele();
        }
        
    }//GEN-LAST:event_shtoProduktinMousePressed
    public boolean kontrolloSasin(){
        int sasiaAktuale = Integer.parseInt(sasiaField.getText());
        boolean t = false;
        if (this.sasia < sasiaAktuale) {            
            t = true;
        }
        return t;
    }
    private void selektoProduktinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selektoProduktinMousePressed
        SelektoProduktin s = new SelektoProduktin();
        SelektoProduktin.thirrja = "Shitje";
        s.setVisible(true);
    }//GEN-LAST:event_selektoProduktinMousePressed

    private void printoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printoMousePressed
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        boolean t = true;
        if (nRow == 0) {
            alert1.setText("Nuk keni shtuar asnje produkt!");
            t = false;
        }
        
        double totali = 0;
        if(t){
            
            int periudhaKohore = Integer.parseInt(kohaField.getText());
            String data = data(), year = viti();
            
            
            for (int i = 0; i <nRow; i++) {
                
                        String cms = String.valueOf(dtm.getValueAt(i, 7));
                        double cm = Double.parseDouble(cms.substring(0,cms.length()-1));                   
                        totali += cm;
                
            }
            int garancioniId = 0;
            String nrId = "null";
            try{
                String dataSkadimit = llogaritDatenSkadimit(periudhaKohore);
                
                Statement s = prg.con().createStatement();
                s.execute("Insert into garancioni (dataGarancionit,totali,kohaGarancionit,dataSkadimit) values('"+data+"','"+totali+"','"+periudhaKohore+" Muaj','"+dataSkadimit+"')");            
                ResultSet rs = s.executeQuery("Select garancioniID from garancioni where dataGarancionit = '"+data+"' and totali = '"+totali+"' and kohaGarancionit = '"+periudhaKohore+" Muaj'");
                while(rs.next()){
                    garancioniId = rs.getInt(1);
                }
                nrId = "G"+garancioniId+"-"+year;
                s.execute("Update garancioni set nrIdentifikues = '"+nrId+"' where garancioniID = '"+garancioniId+"'");
                komenti = dataSkadimit;
                s.execute("Insert into transaksionet (kategoria,nrIdentifikimit,totali,dataTransaksionet,perdoruesi,klienti,komenti) values ('Shitje','"+nrId+"','"+totaliShitjes()+"','"+data+"','"+prg.emriPerdoruesit+"','Klient Privat','"+komenti+"')");

            }catch(SQLException e){
                e.printStackTrace();
            }
            for (int i = 0; i < nRow; i++) {
                Vector v = new Vector();
                for (int j = 0; j < nCol; j++) {
                    String s = String.valueOf(dtm.getValueAt(i, j));
                    v.add(s);
                }
                
                try{
                    
                    int sasia = Integer.parseInt(String.valueOf(v.get(4)));
                    String ce = String.valueOf(v.get(6));
                    String heqjaEuro = ce.substring(0,ce.length()-1);
                    
                    double cmimi = Double.parseDouble(heqjaEuro);
                    
                    double totaliRreshtit = cmimi*sasia;
                    
                    
                    Statement s = prg.con().createStatement();
                    s.execute("Insert into daljetG (nrRendor,produkti,pershkrimi,sasia,Njesia,cmimi,totali,nrIdentifikues,garancioniId,idProduktit) values ('"+v.get(0)+"','"+v.get(2)+"','"+v.get(3)+"','"+v.get(4)+"'"
                            + ",'"+v.get(5)+"','"+v.get(6)+"','"+totaliRreshtit+" €','"+nrId+"','"+garancioniId+"','"+v.get(1)+"')");
                    
                    
                }catch(SQLException e){
                    e.printStackTrace();
                }
                
            }
            pdfShitje.nrIdentifikues = nrId;
            pdfShitje.periudhaKohore = periudhaKohore;
            if (jCheckBox1.isSelected()) {
                pdfShitje.shkruaj();
                alert1.setText("Garancioni u Printua!");
            }else
                alert1.setText("Shitja u regjistrua!");
            minusoStokin();
                      
        }
    }//GEN-LAST:event_printoMousePressed
    public String llogaritDatenSkadimit(int periudhaKohore){
        LocalDate dateObj = LocalDate.now();
        LocalDate plusmonths = dateObj.plusMonths(periudhaKohore);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String date = plusmonths.format(formatter);
        
        return date;
    }
    public  double totaliShitjes(){
        
        double totaliShitjes = 0;
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        for (int i = 0; i < nRow; i++) {
                Vector v = new Vector();
                for (int j = 0; j < nCol; j++) {
                    String s = String.valueOf(dtm.getValueAt(i, j));
                    v.add(s);
                }
                int sasia = Integer.parseInt(String.valueOf(v.get(4)));
                    String ce = String.valueOf(v.get(6));
                    String heqjaEuro = ce.substring(0,ce.length()-1);
                    
                    double cmimi = Double.parseDouble(heqjaEuro);
                    
                    double totaliRreshtit = cmimi*sasia;
                     totaliShitjes = totaliRreshtit * dtm.getRowCount();
    
        }
        return totaliShitjes;
    }
    
    public void minusoStokin(){
        int sasia = 0,produktiId = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            
                produktiId = Integer.parseInt(String.valueOf(jTable1.getValueAt(i, 1)));
                sasia = Integer.parseInt(String.valueOf(jTable1.getValueAt(i, 4)));
                
                try{
                    Statement s = prg.con().createStatement();
                    s.execute("Update Produkti set Sasia = Sasia -"+sasia+" where ProduktiID = "+produktiId);
                }catch(SQLException e){
                    e.printStackTrace();
                }
        }
    }
   /* public String llogaritDitet(String data,String dataSkadimit){
        LocalDate dataAktuale = LocalDate.parse(data, DateTimeFormatter.ISO_DATE);
        long t= ChronoUnit.DAYS.between(data,dataSkadimit);
        
    }*/
    public String data(){
        LocalDate dateObj = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String date = dateObj.format(formatter);
        return date;
    }
    public String viti(){
        LocalDate dateObj = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy");
        String date = dateObj.format(formatter);
        return date;
    }
    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        if (jTable1.getSelectionModel().isSelectionEmpty()) {
            alert1.setText("Nje Rresht Duhet Te Selektohet!");
            
        }else{
            int row = jTable1.getSelectedRow();          
            ((DefaultTableModel)jTable1.getModel()).removeRow(row);  
            rregulloNumratRendor(row);
            nrRreshtit--;
        }
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MousePressed
        String pathName = Login.folderiGarancioneve;
        try {
            Desktop.getDesktop().open(new File(pathName));
        } catch (IOException ex) {
           
        }
    }//GEN-LAST:event_jButton10MousePressed
     public void rregulloNumratRendor(int row){
        row++;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            int vlera = Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(i, 0)));
            if (row < vlera) {                            
                Object x = (Integer) row;
                jTable1.setValueAt(x, i, 0);
                row++;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shitje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shitje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shitje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shitje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shitje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel alert1;
    private javax.swing.JLabel cmiT;
    private static javax.swing.JTextField cmimiField;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private static javax.swing.JTextField kohaField;
    private static javax.swing.JTextField njesiaField;
    private javax.swing.JLabel perT;
    private static javax.swing.JTextField pershkrimiField;
    private javax.swing.JLabel pkT;
    private javax.swing.JButton printo;
    private javax.swing.JLabel proT;
    private static javax.swing.JTextField produktiField;
    private javax.swing.JLabel sasT;
    private javax.swing.JLabel sasT1;
    private static javax.swing.JTextField sasiaField;
    private javax.swing.JButton selektoProduktin;
    private javax.swing.JButton shtoProduktin;
    // End of variables declaration//GEN-END:variables

}
