/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programi;
import java.awt.geom.RoundRectangle2D;
import java.sql.*;
import java.util.Vector;
/**
 *
 * @author Pc
 */
public class shtoPerdorues extends javax.swing.JFrame {
    private Vector v = new Vector();
    /**
     * Creates new form shtoPerdorues
     */
    public shtoPerdorues() {
        initComponents();
        loadPerdoruesit();
        this.setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
    }
    public void loadPerdoruesit(){
        try{
            Statement s = prg.con().createStatement();
            ResultSet rs = s.executeQuery("Select emriPerdoruesit from useri");
            while(rs.next()){
                v.add(rs.getString(1));
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        emriP = new javax.swing.JLabel();
        epField = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        pField = new javax.swing.JTextField();
        emriB = new javax.swing.JLabel();
        emriBField = new javax.swing.JTextField();
        nrB = new javax.swing.JLabel();
        nrBField = new javax.swing.JTextField();
        adresa = new javax.swing.JLabel();
        adField = new javax.swing.JTextField();
        nrF = new javax.swing.JLabel();
        nrFField = new javax.swing.JTextField();
        nrT = new javax.swing.JLabel();
        nrTField = new javax.swing.JTextField();
        alert1 = new javax.swing.JLabel();
        alert2 = new javax.swing.JLabel();
        alert7 = new javax.swing.JLabel();
        xh = new javax.swing.JLabel();
        shtoProduktin = new javax.swing.JButton();
        choice1 = new java.awt.Choice();
        jButton6 = new javax.swing.JButton();
        nrT1 = new javax.swing.JLabel();
        shtoX = new javax.swing.JTextField();
        plus = new javax.swing.JButton();
        alert3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(119, 236, 145));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        jButton2.setBackground(new java.awt.Color(255, 255, 241));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/arrow.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        emriP.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        emriP.setText("Emri i Perdoruesit:");

        epField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        epField.setToolTipText("");

        pass.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        pass.setText("Passwordi:");

        pField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        pField.setToolTipText("");

        emriB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        emriB.setText("Emri i Biznesit:");

        emriBField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        emriBField.setToolTipText("");

        nrB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nrB.setText("Nr.Biznesit:");

        nrBField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nrBField.setToolTipText("");

        adresa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        adresa.setText("Adresa:");

        adField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        adField.setToolTipText("");

        nrF.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nrF.setText("Nr.Fiskal:");

        nrFField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nrFField.setToolTipText("");

        nrT.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nrT.setText("Nr.Telefonit:");

        nrTField.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nrTField.setToolTipText("");

        alert1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        alert1.setForeground(new java.awt.Color(255, 51, 0));

        alert2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        alert2.setForeground(new java.awt.Color(255, 51, 0));

        alert7.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        alert7.setForeground(new java.awt.Color(255, 51, 0));

        xh.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        xh.setText("Xhirollogaritë:");

        shtoProduktin.setBackground(new java.awt.Color(255, 255, 0));
        shtoProduktin.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        shtoProduktin.setText("Shto Perdorues");
        shtoProduktin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shtoProduktin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                shtoProduktinMousePressed(evt);
            }
        });

        choice1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N

        jButton6.setBackground(new java.awt.Color(119, 236, 145));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/x.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        nrT1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nrT1.setText("Shto Xhirollogari:");

        shtoX.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        shtoX.setToolTipText("");

        plus.setBackground(new java.awt.Color(119, 236, 145));
        plus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/plus.png"))); // NOI18N
        plus.setBorder(null);
        plus.setContentAreaFilled(false);
        plus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                plusMousePressed(evt);
            }
        });
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        alert3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        alert3.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pass)
                            .addComponent(emriP)
                            .addComponent(emriB)
                            .addComponent(nrB)
                            .addComponent(adresa)
                            .addComponent(nrF)
                            .addComponent(nrT)
                            .addComponent(xh)
                            .addComponent(nrT1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emriBField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nrBField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(epField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alert1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(alert2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alert7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(217, 217, 217)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nrTField)
                                        .addComponent(nrFField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(shtoX, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alert3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shtoProduktin)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emriP, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(epField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(alert1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(alert2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emriB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emriBField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nrB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrBField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrF, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrFField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alert7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrT, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(alert3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nrT1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(shtoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shtoProduktin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        Parametrat p= new Parametrat();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void shtoProduktinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shtoProduktinMousePressed
        alert1.setText("");
        alert2.setText("");
        alert3.setText("");
        check();
    }//GEN-LAST:event_shtoProduktinMousePressed
    public void check(){
        boolean t = true;
        if (epField.getText() == null || epField.getText().trim().isEmpty()) {
            alert1.setText("!");
            return;
        }
        for (int i = 0; i < v.size(); i++) {
            if (epField.getText().equals(v.get(i))) {
                alert1.setText("!");
                t = false;
            }
        }
        if (pField.getText() == null || pField.getText().trim().isEmpty()) {
            alert2.setText("!");
            return;
        }
        
        if (t) {
            shto();
        }
    }
    public void shto(){
        String ep = epField.getText();
        String p = pField.getText();
        String eb = emriBField.getText();
        String nrB = nrBField.getText();
        String ad = adField.getText();
        String nrF = nrFField.getText();
        String nrT = nrTField.getText();
        int userId = 0;
        try{
            System.out.println("Item Count:"+choice1.getItemCount());
            Statement s = prg.con().createStatement();
            s.execute("Insert into useri (emriPerdoruesit,passwordi,emriFirmes,nrBiznesit,Adresa,nrFiskal,nrTelefonit,Xhirollogaria) values "
                    + "('"+ep+"','"+p+"','"+eb+"','"+nrB+"','"+ad+"','"+nrF+"','"+nrT+"','"+choice1.getItemCount()+"')");
            ResultSet rs = s.executeQuery("Select userID from useri where emriPerdoruesit = '"+ep+"'");
            while(rs.next()){
                System.out.println(rs.getInt(1));
                userId = rs.getInt(1);
            }
            for (int i = 0; i < choice1.getItemCount(); i++) {
                System.out.println("Inside times:"+i);
                s.execute("Insert into xhirot (Xhirollogaria,userId) values  ('"+choice1.getItem(i)+"','"+userId+"')");
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        Parametrat pa = new Parametrat();
        pa.setVisible(true);
        dispose();
    }
    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed

        int pozita = choice1.getSelectedIndex();
        choice1.remove(pozita);

    }//GEN-LAST:event_jButton6MousePressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void plusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMousePressed
        boolean x = true;
        if ( shtoX.getText() == null || shtoX.getText().trim().isEmpty()) {
            alert3.setText("!");
            x = false;
        }
        for (int i = 0; i < choice1.getItemCount(); i++) {
            if (shtoX.getText().equals(choice1.getItem(i))) {
                alert3.setText("!");
                x = false;
            }
        }
        if (x) {
            choice1.add(shtoX.getText());
        }

    }//GEN-LAST:event_plusMousePressed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shtoPerdorues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shtoPerdorues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shtoPerdorues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shtoPerdorues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shtoPerdorues().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField adField;
    private javax.swing.JLabel adresa;
    private javax.swing.JLabel alert1;
    private javax.swing.JLabel alert2;
    private javax.swing.JLabel alert3;
    private javax.swing.JLabel alert7;
    private static java.awt.Choice choice1;
    private javax.swing.JLabel emriB;
    private static javax.swing.JTextField emriBField;
    private javax.swing.JLabel emriP;
    public static javax.swing.JTextField epField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nrB;
    private static javax.swing.JTextField nrBField;
    private javax.swing.JLabel nrF;
    private static javax.swing.JTextField nrFField;
    private javax.swing.JLabel nrT;
    private javax.swing.JLabel nrT1;
    private static javax.swing.JTextField nrTField;
    public static javax.swing.JTextField pField;
    private javax.swing.JLabel pass;
    private javax.swing.JButton plus;
    private javax.swing.JButton shtoProduktin;
    private static javax.swing.JTextField shtoX;
    private javax.swing.JLabel xh;
    // End of variables declaration//GEN-END:variables
}
