/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programi;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Vector;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Pc
 */
public class Transaksionet extends javax.swing.JFrame {

    public Transaksionet() {
        initComponents();
        loadtable();
        this.setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        TableColumnModel t = jTable1.getColumnModel();
        t.getColumn(0).setPreferredWidth(50);
        t.getColumn(1).setPreferredWidth(110);
        t.getColumn(2).setPreferredWidth(150);
        t.getColumn(3).setPreferredWidth(130);
        t.getColumn(4).setPreferredWidth(130);
        t.getColumn(5).setPreferredWidth(130);
        t.getColumn(6).setPreferredWidth(130);
        t.getColumn(7).setPreferredWidth(150+87);
        search();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        ndrysho = new javax.swing.JButton();
        alert1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(119, 236, 145));

        jButton2.setBackground(new java.awt.Color(255, 255, 241));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/arrow.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 255, 254));
        jTable1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kategoria", "Klienti", "Nr Identifikimit", "Totali", "Data", "Perdoruesi", "Komenti"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(10);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        searchField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jButton3.setBackground(new java.awt.Color(255, 255, 241));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/x.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        ndrysho.setBackground(new java.awt.Color(255, 255, 241));
        ndrysho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ndrysho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programi/data/1064 (1).png"))); // NOI18N
        ndrysho.setBorder(null);
        ndrysho.setBorderPainted(false);
        ndrysho.setContentAreaFilled(false);
        ndrysho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ndrysho.setMargin(new java.awt.Insets(10, 10, 10, 10));
        ndrysho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ndryshoMousePressed(evt);
            }
        });

        alert1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        alert1.setForeground(new java.awt.Color(255, 51, 0));
        alert1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alert1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addComponent(ndrysho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 93, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ndrysho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(alert1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     public void search(){
        
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        TableRowSorter sorter = new TableRowSorter<>(dt);
        jTable1.setRowSorter(sorter);
        
        searchField.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
            search(searchField.getText());
         }
         @Override
         public void removeUpdate(DocumentEvent e) {
            search(searchField.getText());
         }
         @Override
         public void changedUpdate(DocumentEvent e) {
            search(searchField.getText());
         }
         public void search(String str) {
            if (str.length() == 0) {
               sorter.setRowFilter(null);
            } else {
               sorter.setRowFilter(RowFilter.regexFilter("(?i)" + str));
            }
         }
      });
     }
    public void loadtable(){
         DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        try{
            Statement s = prg.con().createStatement();
            ResultSet rs = s.executeQuery("Select * from transaksionet");
            while(rs.next()){
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(7));
                v.add(rs.getString(3));
                v.add(rs.getString(4)+" €");
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                if (rs.getString(2).equals("Shitje")) {
                    String dataSkadimit = rs.getString(8);
                    String dataGarancionit = rs.getString(5);
                    long ditet = llogaritDitet(dataSkadimit);
                    if (ditet == 0 || ditet < 0) {
                        v.add("I Skaduar");
                    }else
                        v.add("Ditet e mbetura: "+ditet);
                }
                
                dt.addRow(v);
                
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        Fillimi r= new Fillimi();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MousePressed
    public long llogaritDitet(String dataSkadimit){
        
        String dataAktuale = data();       
        LocalDate l = LocalDate.parse(dataAktuale);
        LocalDate s = LocalDate.parse(dataSkadimit);
        
        long t= ChronoUnit.DAYS.between(l,s);
        return t;
    }
    public String data(){
        LocalDate dateObj = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String date = dateObj.format(formatter);
        return date;
    }
    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        if (jTable1.getSelectionModel().isSelectionEmpty()) {
            alert1.setText("Nje Rresht Duhet Te Selektohet!");

        }else{
            int row = jTable1.getSelectedRow();
            String nrIdentifikimit = jTable1.getModel().getValueAt(row, 3).toString();
            String lloji = jTable1.getModel().getValueAt(row, 1).toString();
            if (lloji.equals("Faturë")) {
                fshiFaturen(nrIdentifikimit);
                ((DefaultTableModel)jTable1.getModel()).removeRow(row);
                alert1.setText("Fatura eshte anuluar!");
            }
            if (lloji.equals("Ofertë")) {
                fshiOferten(nrIdentifikimit);
                ((DefaultTableModel)jTable1.getModel()).removeRow(row);
                alert1.setText("Oferta eshte anuluar!");
            }
            if (lloji.equals("Shitje")) {
                fshiShitjen(nrIdentifikimit);
                ((DefaultTableModel)jTable1.getModel()).removeRow(row);
                alert1.setText("Shitja eshte anuluar!");
            }
           // 
            
            
        }
    }//GEN-LAST:event_jButton3MousePressed
    public void fshiFaturen(String nrId){
        String klienti = null;
          try{
              Statement s = prg.con().createStatement();
              s.execute("Delete from transaksionet where nrIdentifikimit = '"+nrId+"'");
              ResultSet rs = s.executeQuery("Select sasia,idProduktit,klienti from daljetFaturore where nrIdentifikues = '"+nrId+"'");
              while(rs.next()){
                  klienti = rs.getString(3);
                    int sasia = rs.getInt(1);
                    int id = rs.getInt(2);
                    Statement s2 = prg.con().createStatement();
                    s2.execute("Update produkti set sasia = sasia+"+sasia+" where ProduktiID = "+id);                                                      
              }
              Statement s3 = prg.con().createStatement();
              s3.execute("Delete from daljetFaturore where nrIdentifikues = '"+nrId+"'");
              s3.execute("Delete from fatura where nrIdentifikues = '"+nrId+"'");
              
               File myObj = new File(Login.folderiFaturave+"//"+klienti+" #"+nrId+".pdf"); 
              if (myObj.delete()) {
                System.out.println("Deleted");
            }else
                  System.out.println("Failed to delete");
          }catch(SQLException e){
              e.printStackTrace();
          }
    }
    public void fshiOferten(String nrId){
        String klienti = null;
           try{
              Statement s = prg.con().createStatement();
              s.execute("Delete from transaksionet where nrIdentifikimit = '"+nrId+"'");
              ResultSet rs = s.executeQuery("Select Klienti from fatura where nrIdentifikues = '"+nrId+"'");
              while(rs.next()){
                  klienti = rs.getString(1);
              }
              Statement s1 = prg.con().createStatement();
              s1.execute("Delete from daljetFaturore where nrIdentifikues = '"+nrId+"'");
              s1.execute("Delete from fatura where nrIdentifikues = '"+nrId+"'");
              File myObj = new File(Login.folderiOfertave+"//"+klienti+" #"+nrId+".pdf"); 
              if (myObj.delete()) {
                System.out.println("Deleted");
            }else
                  System.out.println("Failed to delete");
          }catch(SQLException e){
              e.printStackTrace();
          }
    }
    public void fshiShitjen(String nrId){
        try{
              Statement s = prg.con().createStatement();
              s.execute("Delete from transaksionet where nrIdentifikimit = '"+nrId+"'");
              ResultSet rs = s.executeQuery("Select sasia,idProduktit from daljetG where nrIdentifikues = '"+nrId+"'");
              while(rs.next()){
                    int sasia = rs.getInt(1);
                    int id = rs.getInt(2);
                    Statement s2 = prg.con().createStatement();
                    s2.execute("Update produkti set sasia = sasia+"+sasia+" where ProduktiID = "+id);                                                      
              }
              Statement s3 = prg.con().createStatement();
              s3.execute("Delete from daljetG where nrIdentifikues = '"+nrId+"'");
              s3.execute("Delete from garancioni where nrIdentifikues = '"+nrId+"'");
              File myObj = new File(Login.folderiGarancioneve+"//"+nrId+".pdf"); 
              if (myObj.delete()) {
                System.out.println("Deleted");
            }else
                  System.out.println("Failed to delete");
          }catch(SQLException e){
              e.printStackTrace();
          }
    }
    private void ndryshoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ndryshoMousePressed
        if (jTable1.getSelectionModel().isSelectionEmpty()) {
            alert1.setText("Nje Rresht Duhet Te Selektohet!");

        }else{
            int row = jTable1.getSelectedRow();
            String kategoria = jTable1.getModel().getValueAt(row, 1).toString();
            if (kategoria.equals("Faturë")) {
                ndryshoFaturen nf = new ndryshoFaturen();
                nf.setVisible(true);
                dispose();
            }else if(kategoria.equals("Shitje")){
                ndryshoShitje ns = new ndryshoShitje();
                ns.setVisible(true);
                dispose();
            }else if(kategoria.equals("Ofertë")){
                 ndryshoOferten no = new ndryshoOferten();
                 no.setVisible(true);
                 dispose();
            }
        }
        
    }//GEN-LAST:event_ndryshoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksionet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksionet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksionet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksionet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksionet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel alert1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton ndrysho;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
